bookslib/bookslib/Components/TopBooksViewComponent.cs
using bookslib.Repository;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace bookslib.Components
{
    public class TopBooksViewComponent: ViewComponent
    {
        private readonly BookRepository _bookRepository;

        public TopBooksViewComponent(BookRepository bookRepository)
        {
            _bookRepository = bookRepository;
        }
        public async Task<IViewComponentResult> InvokeAsync(int count)
        {
            var books = await _bookRepository.GetTopBooksAsync(count);
            return View(books);
        }
    }
}

bookslib/bookslib/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Dynamic;
using bookslib.Models;
using Microsoft.Extensions.Configuration;

namespace bookslib.Controllers
{
    public class HomeController : Controller
    {
        private readonly IConfiguration configuration;
        public HomeController(IConfiguration _configuration)
        {
            configuration =  _configuration;
        }
        public ViewResult Index()
        {
            //var value = _messageRepository.GetName();

            //var newBook = configuration.GetSection("NewBookAlert");
            //var result = newBook.GetValue<bool>("DisplayNewBookAlert");
            //var bookName = newBook.GetValue<string>("BookName");

            var result = configuration["AppName"];
            var key1 = configuration["infoObj:key1"];
            var key2 = configuration["infoObj:key2"];
            var key3 = configuration["infoObj:key3:key3obj1"];


            return View();
        }
        public ViewResult AboutUS(int id)
        {
            return View();
        }
        public ViewResult ContactUS()
        {
            return View();
        }
    }
}

bookslib/bookslib/Views/Home/AboutUs.cshtml
@{
    ViewData["Title"] = "About Us";
}
@section breadcrum {
    <nav aria-label="breadcrum">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item"><a href="#">Page 1</a></li>
            <li class="breadcrumb-item active" aria-current="page"><a href="#">About us</a></li>

        </ol>
    </nav>
}
<h1 class="h1">This is the About Us page of the application</h1>

bookslib/bookslib/Views/Home/ContactUS.cshtml
@{
    ViewData["Title"] = "Contact Us";
}

@section breadcrum {
    <nav aria-label="breadcrum">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item"><a href="#">Page 1</a></li>
            <li class="breadcrumb-item active" aria-current="page"><a href="#">Contact us</a></li>

        </ol>
    </nav>
}
<h1>ContactUS</h1>

bookslib/bookslib/Views/Home/Index.cshtml
@{ ViewData["Title"] = "Home"; }
@inject bookslib.Repository.IBookRepository _bookrepository
<section class="jumbotron text-center">
    <div class="container">
        <h1>Welcome to Bookstore</h1>
        <p class="lead text-muted">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
            quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
        </p>
        <p>
            <a href="#" class="btn btn-primary my-2">Search books</a>
        </p>
        @foreach(var item in await _bookrepository.GetAllBooks())
        {
            <h2>@item.Title</h2>
        }
    </div>
</section>


<div class="py-5 bg-light">
    <div class="container">
        <h3 class="h3">Top books</h3>
        @await Component.InvokeAsync("TopBooks", new { count = 3 })

        @*<vc:top-books count="6" ></vc:top-books>*@

    </div>
</div>



@section scripts{
    <script>
        $(document).ready(function () {
            //alert("document is ready");
        })
    </script>
}